.gitlab-ci.yml

To trigger a build of the APT repository on changes in mender-connect.

[pipeline] Add trigger:mender-dist-packages job

---

examples/mender-connect.conf

This parameter is not required, as the ServerURL is retrieved from the
mender client via D-Bus API.

[examples/mender-connect.conf] Remove unnecessary ServerURL

---

examples/mender-connect.conf

This parameter is not required, as the ServerURL is retrieved from the
mender client via D-Bus API.
Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
(cherry picked from commit 6ede6fea0b0d8955df3eccf208e010f532d1b009)

1.0.x: [examples/mender-connect.conf] Remove unnecessary ServerURL

---

app/daemon.go

This was left out by mistake when introducing the handshake.

Inform session if terminal feature is enabled

---

app/daemon.go
config/config.go
config/config_test.go
limits/filetransfer/limits.go
limits/filetransfer/limits_test.go
session/filetransfer.go
session/filetransfer_test.go
session/model/filetransfer.go
utils/fs.go
utils/fs_test.go

MEN-4325 File Transfer Limits

---

session/filetransfer.go
session/filetransfer_test.go

This is not the complete implementation that we talked about during the backend team meeting. I realized that adding the filename parameter will require updates to all dependencies as well, as this will introduce a new model in go-lib-micro (right now we're reusing the FileInfo model for the upload).

stat(2) file path and verify conditions before starting upload

---

.gitlab-ci.yml

while working on QA-315 and to prevent costly trigger loops from appearing because of that, this switches the trigger jobs to use the gitlab native trigger functionality (which also allows easier pipeline navigation).
working triggering pipeline: https://gitlab.com/Northern.tech/Mender/mender-connect/-/pipelines/315074399
triggered pipelines (canceled as it was just for debug purposes):
- [mender-qa](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/315079395)
- [mender-dist-packages](https://gitlab.com/Northern.tech/Mender/mender-dist-packages/-/pipelines/315079397)
- [integration](https://gitlab.com/Northern.tech/Mender/integration/-/pipelines/315079388)
this depends on mendersoftware/mender-qa#506
also: coveralls is drunk!

make use of gitlab triggers - relates to QA-315

---

connectionmanager/connectionmanager.go

Changelog: MEN-4694: Handle the re-connection request even if there is
no new JWT token from the Mender client
(cherry picked from commit ea08acc12949d44e1b8a181f75c438b9930a29e9)
(cherry picked from commit f806a0f7a2ce6f06543a531b3c12af5549d3d183)

MEN-4694 Break reconnection loop on auth lost

---

app/daemon.go
app/daemon_test.go
connection/connection.go
connectionmanager/connectionmanager.go

This commit merges the dbusEventLoop and eventLoop into a single
eventLoop routine, since separating the reconnection logic can lead to
unintended short-circuit loops if the device becomes decommissioned.
changelog: title
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>

[MEN-4864] Try refreshing JWT token if server returns 401 (unauthorized)

---

app/daemon.go
app/daemon_test.go
connection/connection.go
connectionmanager/connectionmanager.go

This reverts commit 8a76f5930ecff4137d525ed3b0382853ccebe381, reversing
changes made to 48044ce5f0e6921a6ea72668f280590195b3108f.
@lluiscampos False alarm, after trying to debug for several hours I realized that I have been using mender-connect 1.1.0 without knowing :man_facepalming: 
In any case, I am unable to reproduce the issue after #37 was merged.

Revert "Merge pull request #42 from alfrunes/MEN-4864"

---

app/daemon.go

In both cases will make the whole info level logging more readable.
On start, the last message of regular operations ends with "waiting for
JWT token", so let's inform the user when the token was retrieved and
the connection is up and running.
Similarly, on re-connections, the user is left with "waiting for
reconnect", so inform the user when the re-connection happened.

Add couple of info logs to make logging symmetric

---

app/daemon.go
app/daemon_shell.go
app/daemon_test.go

The global setting of total spawned shells guards against a
potential resource exhaustion on a device running mender-connect.
However not in all cases the count was decremented. Adding:
* global, thread-safe function to decrement the shells count
* decrement the count on terminate all
* decrement the count on expired sessions
* decrement the count when stopping sessions by user id
ChangeLog:title

fix: Global spawned shells count is not always decremented.

---

config/config.go

feat: assume `/bin/sh` when deploying on platforms without `/etc/shells`
Specifically required when deploying on a platform where standard folders (including but not limited to `/etc`)  are read-only (e.g., [Berghof PLC](https://www.berghof-automation.com/en/products/compact-control-system/b-fortis-cc-slim)). On these platforms `/etc/shells` cannot be added (if missing).
Signed-off-by: Uri Ishon uishon@gmail.com

assume /bin/sh as default shell when no /etc/shells file

---

LICENSE
LIC_FILES_CHKSUM.sha256

Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
(cherry picked from commit 1ae421b70a288157e6785e6a923d694fcea2863d)

chore: Update license copyright to 2023

---

.gitlab-ci.yml

So that it produces a junit report that can be parsed by CI.

ci: Update unit tests job to the latest template

---

support/mender-connect.service

Changelog: `mender-connect` systemd service can use either the old
`mender-client` service or the new `mender-authd` service, which is the
name of the authentication daemon of new Mender client. They are both
kept as `Wants` and not `Require` so that `mender-connect` can run with
either.

MEN-6858: Update sytemd service for the new client service

---

LICENSE
LIC_FILES_CHKSUM.sha256

Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
(cherry picked from commit 42c6ed2973fd43ae267b1f4dac5009dc606cfa2a)

chore: Update license copyright to 2024

---

LICENSE
LIC_FILES_CHKSUM.sha256

(cherry picked from commit 42c6ed2973fd43ae267b1f4dac5009dc606cfa2a)

2.1.x: chore: Update license copyright to 2024

---

app/daemon.go
app/daemon_test.go
connectionmanager/connectionmanager.go
connectionmanager/connectionmanager_test.go
connectionmanager/exponentialbackoff.go
session/session_test.go
shell/exec_test.go

Exponentially backs off until max (5 minutes) is reached. It will then keep retrying every 5 minutes.
Ticket: MEN-5782

feat: added back-off in connectionmanager

---

connectionmanager/connectionmanager.go
connectionmanager/connectionmanager_test.go
connectionmanager/exponentialbackoff.go

The previous backoff had a starting interval at 1
minute and a max backoff at 60 minutes. When it reached 60 minutes it
would linearly increase to 120 minutes minutes where it would keep
retrying.
The backoff will now start at 1 second and exponentially increase after
3 retries until it reaches 30 minutes where it will keep retrying.
For each interval a jitter between 0 and 5 seconds will be added.
Ticket: ME-546
Changelog: Commit

feat: lower backoff intervals

---

app/daemon.go
app/daemon_shell.go
session/session_test.go
session/shell.go
shell/shell.go
shell/shell_test.go

Changelog: Preserve group assignments by retrieving GIDs for users and adding them when executing a shell.
Ticket: ME-530

fix: preserve group assignments
