mendersoftware/mender-connect

app/daemon.go
app/daemon_test.go
shell/exec.go

MEN-4307: send error messages when receiving unknown proto/type values

---

app/daemon.go
config/config.go
session/session.go
shell/shell.go
shell/shell_test.go

Get user's home directory and use it as cwd and HOME env var value

---

app/daemon.go
app/daemon_test.go
client/dbus/dbus.go
client/dbus/dbus_libgio.go
client/dbus/mocks/DBusAPI.go
client/mender/auth.go
client/mender/mocks/AuthClient.go
connectionmanager/connectionmanager.go
connectionmanager/connectionmanager_test.go

Allow to exit from mender-connect when waiting for the JWT token

---

app/daemon.go
app/daemon_test.go
client/dbus/dbus.go
client/dbus/dbus_libgio.go.h
client/dbus/dbus_libgio_response.go
client/dbus/mocks/DBusCallResponse.go
client/mender/auth.go
client/mender/auth_test.go
client/mender/mocks/AuthClient.go

MEN-4360: Extend the D-Bus API client to fetch the server URL

---

.gitlab-ci.yml

1.0.x: [pipeline] Add trigger:mender-qa job

---

session/filetransfer.go
session/filetransfer_test.go

stat(2) file path and verify conditions before starting upload

---

limits/filetransfer/limits.go
limits/filetransfer/limits_test.go

File Transfer limits: owner and group fix.

---

limits/filetransfer/limits.go

File transfer moving exp avg: misspell fixes.

---

app/daemon.go
app/daemon_shell.go
config/config.go
config/config_test.go
config/paths.go
session/shell.go
shell/shell.go
shell/shell_test.go

Along with some minor nitpicks and spelling fixes.

MEN-4505: Fix terminal PATH issue by defaulting to a login shell on spawn

---

connectionmanager/connectionmanager.go

MEN-4694 Break reconnection loop on auth lost

---

LICENSE
LIC_FILES_CHKSUM.sha256

Changelog: None
Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
(cherry picked from commit ea30e2a5562db2b4806d2989e965055e9f6f9201)

Update license to 2022

---

app/daemon_test.go

style: Additional formatting in tests

---

.gitlab-ci.yml

* adding the GOLANG_VERSION variable, read by apckage builders
ChangeLog:none

MEN-5459 Install go based on the source repository preferences.

---

.gitlab-ci.yml

Fixing the go lang version set for package build.

---

.gitlab-ci.yml

feat: build using golang version 1.17.13

---

client/dbus/dbus_libgio.go
client/dbus/dbus_libgio_helpers.go
client/dbus/dbus_libgio_response.go
config/config.go
connection/connection.go
utils/fs.go

chore: go fmt: required formatting.
Ticket: None

go fmt: required formatting.

---

client/dbus/dbus_libgio.go.h
client/dbus/error.go.h

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

chore: Add license headers to C header files.

---

client/dbus/dbus_libgio.go
client/dbus/dbus_libgio_helpers.go
client/dbus/dbus_libgio_response.go
config/config.go
connection/connection.go
utils/fs.go

Ticket: None
(cherry picked from commit e287fada705d93095eafeb2933b0adc4290bfcb3)

chore: go fmt: required formatting.

---

connectionmanager/connectionmanager_test.go
session/portforward_test.go

Resubmit of #90 fixing formalities.

test: Fix racing connection tests

---

limits/filetransfer/limits_test.go

Resubmit of #89 fixing formalities.

test: Fix limits test user name mixup

---

connectionmanager/connectionmanager_test.go
session/portforward_test.go

[cherry-picks] test: sudden failures: increasing timeouts.

---

.gitlab-ci.yml

feat: build and test using the latest version of golang (1.21 today)

---

session/menderclient.go

Changelog: In Mender client v4.0, the `mender` binary has been split into `mender-update` and `mender-auth`. Modify `mender-connect` to call the right binary to trigger `check-update` and `send-inventory` Ticket: MEN-6671

MEN-6827: Support new CLI interface of the mender client

---

.gitlab-ci.yml

And clean-up the existing build and test jobs.

QA-765: Add an explicit compatibility test

---

LICENSE
LIC_FILES_CHKSUM.sha256

chore: Bump copyright license year to 2025

---

.gitlab-ci.yml
LICENSE
LIC_FILES_CHKSUM.sha256
app/daemon.go
app/daemon_shell.go

Bringing #149 and old #141 to fix the 2.2.x CI pipeline.

2.2.x: Misc CI pipeline fixes
